#!/bin/bash

set -xe

export GOPATH=$PWD/go
export PATH=$GOPATH/bin:$PATH

go get github.com/tools/godep
go get github.com/alecthomas/gometalinter

gometalinter --install

source_dir="$(cd "$(dirname "$0")" && pwd)"
pushd $source_dir/..
  godep restore

  gometalinter --exclude="(Godeps|fakes|_test.go)" --disable=gotype ./... # gotype is broken on golang#1.4.2-wheezy

  go install github.com/onsi/ginkgo/ginkgo
  ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress
popd
